### ISSUE TITLE
unable to connect when install snipe-it version 4.8.0

### ISSUE THREAD

**Issue by changchichung** [mylocaldevstack/snipe-it-ansible-role#1]
I did not change a lot after clone this repository , just modify the snipe-it version to latest (4.8.0)
ansible runs without errors , but after that , I can not open the site , and nginx shows some error , looks like related the mysql ?

```
#1 /opt/snipe-it-4.8.0/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(64): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'root', 'snipeit', Array)
#2 /opt/snipe-it-4.8.0/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(43): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=loca...', 'root', 'snipeit', Array)
#3 /opt/snipe-it-4.8.0/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#4 /opt/snipe-it-4.8.0/vendor...
PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in /opt/snipe-it-4.8.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27
Stack trace:
#0 /opt/snipe-it-4.8.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(27): PDO->__construct('mysql:host=loca...', 'root', 'snipeit', Array)
#1 /opt/snipe-it-4.8.0/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(64): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'root', 'snipeit', Array)
#2 /opt/snipe-it-4.8.0/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(43): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=loca...', 'root', 'snipeit', Array)
#3 /opt/snipe-it-4.8.0/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('my
```

**Comment by changchichung** [comment]
this issue is related to the priviledges in mysql , I add a task to create dbuser and grant priviledges to the database , then the playbook works.
